### ISSUE TITLE
Light bugs when changing uniforms

### ISSUE THREAD

**Issue by paulbaron** [Another-Game-Engine/AGE#408]
The branch "lights" has a very stange bug on lights.
Just the fact of removing the uniform "ambient_color" in the "deferred_shading_point_light.fp" shader triggers the bug.
Adding a uniform "abient_color" to "deferred_shading_merge.fp" also triggers the bug.

**Comment by cesarl** [comment]
@DorianPinaud can you take a look at it please ?

**Comment by DorianPinaud** [comment]
yep

**Comment by cesarl** [comment]
Thx handsome

2015-03-20 17:36 GMT-04:00 DorianPinaud <notifications@github.com>:

> yep
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/issues/408#issuecomment-84155341>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by cesarl** [comment]
I think that i fixed it, look at my last PR
