### ISSUE TITLE
Material Editor : Some material bug during the unserialization 

### ISSUE THREAD

**Issue by DorianPinaud** [Another-Game-Engine/AGE#442]
error :          

throw Exception("Failed to read " + std::to_string(size) + " bytes from input stream! Read " + std::to_string(readSize));

call stack:

![bug](https://cloud.githubusercontent.com/assets/5627999/7205716/2087e2fe-e523-11e4-83f4-1c787df82e5a.JPG)

**Comment by cesarl** [comment]
1 : Mets a jour cereal
https://github.com/USCiLab/cereal/releases/tag/v1.1.1

Ca manque d'infos ton truc :
- Pour quel material ? Tous ou un en particulier ?
- Y a t il une version de serialization pour les material ? Si oui as tu change les infos de serialization de material ? Si oui as tu mis a jour le code pour les differentes versions ?
( a propos des versions) http://uscilab.github.io/cereal/serialization_functions.html 

Ca plante en loadant un int64, peut etre qu'il a ete serialize en int, ou int32 ou autre.
Tout ce qui est serialize doit etre explicite : size_t, uint32_t etc etc

**Comment by DorianPinaud** [comment]
le material tester la c'est alduine.mage

**Comment by cesarl** [comment]
c'est que celui la qui crash ?

Laisse tomber j'ai pas assez d;infos. Je testerais ce WE

**Comment by DorianPinaud** [comment]
y en a plusieurs qui crash. Je m'en fou prend ton temps, c'est loin d’être la priorité actuelle.

**Comment by cesarl** [comment]
bah si c'est un peu grave
mais je ne sais pas en quoi je serais meilleur pour le debugger. M'enfin je
regarde ca demain

Le 17 avril 2015 13:42, DorianPinaud <notifications@github.com> a écrit :

> y en a plusieurs qui crash. Je m'en fou prend ton temps, c'est loin d’être
> la priorité actuelle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/issues/442#issuecomment-94036158>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]
