### ISSUE TITLE
scene which is loaded by asset editor but not by engine core test

### ISSUE THREAD

**Issue by DorianPinaud** [Another-Game-Engine/AGE#454]
@cesarl: si tu pouvait jeter un coup d'oeil

**Comment by cesarl** [comment]
Hé ne pourrais pas avant la semaine prochaine. mais je manque clairement t
d'infos haha. Quelle scene, que ce passe t il etc etc

Le jeu. 23 avr. 2015 17:58, DorianPinaud <notifications@github.com> a
écrit :

**Comment by DorianPinaud** [comment]
En gros j'ai essayé de rajouté une directional light dans la scene MyScene (celle avec sponza). Donc je  suis allé dans l'asset editor j'ai rajouté une directional light, j'ai save. Ensuite j'ai lancé l'engine CoreTest. Pas de directional light dans la scene MyScene. Donc je suis retourné dans l'asset editor, dans le world editor pour voir si j'avais mal save. Dans l'asset editor la scene MyScene à garder la directional light, bizzar. Donc je me susi dit que l'Enginecoretest ne va pas lir les meme fichier que l'asset editor pour charger c'est scene, voila. J'ai pas plus cherché pour le moment donc si t'as une idée la comme ça c'est bienvenu sinon c'est pas grave je suis sur d'autre truc ça urge pas.

**Comment by cesarl** [comment]
Il faut export la scene pour la sauvegarder pour engins core test. Save
c'est que pour l editeur. Sinon je regarderai mercredi qd les copains
seront t partis :)

Le ven. 24 avr. 2015 12:08, DorianPinaud <notifications@github.com> a
écrit :

**Comment by DorianPinaud** [comment]
Ouai ça marche niquel thx !
