### ISSUE TITLE
The asset editor does not always properly quit

### ISSUE THREAD

**Issue by paulbaron** [Another-Game-Engine/AGE#494]

**Comment by paulbaron** [comment]
ThreadTrampoline with the micropprofile does not quit properly

**Comment by cesarl** [comment]
ThreadTrampoline ? C'est quoi ce thread ? Des fois je nomme bizarrement les
choses, mais je ne me souviens pas de celui la haha !

2015-06-20 18:35 GMT-04:00 Paul Baron <notifications@github.com>:

> ThreadTrampoline with the micropprofile does not quit properly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/issues/494#issuecomment-113833482>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by paulbaron** [comment]
C'est le thread de microprofile je crois...
Je ne sais pas si c'est toujours lui qui reste a la fin, il faudrait que ca me le refasse, ce n'est pas systématique.
