### ISSUE TITLE
Fill a Frustum from a Sptolight

### ISSUE THREAD

**Issue by cesarl** [Another-Game-Engine/AGE#502]
pour pouvoir culler 
J'ai mis un hack provisoir dans Camera Render System (un nom du genre)
Branch BFC_Mesh

N'hesite pas si question

**Comment by cesarl** [comment]
cf

https://github.com/Another-Game-Engine/AGE/commit/6f950fa070168cd2f08cab98da39a58af0acc8ab

**Comment by paulbaron** [comment]
Ok
