### ISSUE TITLE
1 : Merge PRs with BFC

### ISSUE THREAD

**Issue by cesarl** [Another-Game-Engine/AGE#509]

**Comment by DorianPinaud** [comment]
ya thibault aussi


2015-08-02 16:29 GMT+01:00 Cesar Leblic <notifications@github.com>:

**Comment by cesarl** [comment]
Lol je crois que tu t'es trompe de thread :)

2015-08-02 11:34 GMT-04:00 DorianPinaud <notifications@github.com>:

> ya thibault aussi
>
>
> 2015-08-02 16:29 GMT+01:00 Cesar Leblic <notifications@github.com>:
>
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Another-Game-Engine/AGE/issues/509>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/issues/509#issuecomment-127036761>
> .
>



-- 
[image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation][image: dancing frog
animation][image: dancing frog animation][image: dancing frog animation][image:
dancing frog animation][image: dancing frog animation]

**Comment by DorianPinaud** [comment]
oh shit !
