### ISSUE TITLE
Les fenêtres ImGUI ne sont plus déplaçables au clic dans l'Asset Editor.

### ISSUE THREAD

**Issue by Lauralie** [Another-Game-Engine/AGE#524]
Between June 29 (my project version) and the release, a bug has been introduced:
Half the time, the dialogs can't be displaced by drag&drop. Nothing happens.

**Comment by cesarl** [comment]
Which exe ?
Release or debug ?
Which scene ? With which assets ?
What's an imgui's dialiog ? That's an imgui's window ?
I need more detail
Ecris les en francais que ca soit plus clair
