### ISSUE TITLE
Crash au clic sur le bouton "save scene"

### ISSUE THREAD

**Issue by Lauralie** [Another-Game-Engine/AGE#526]
Dans l'AssetEditor de release fourni sur le drive (x64 Release) le programme crash lorsque l'on : 
 - Clique sur Save dans la fenêtre Entity List après l'ajout d'un asset dans une scène neuve
 - Clique sur Scene -> Save Scene dans le menu du haut dans une scène déjà sauvegardée (n'importe laquelle)
 - Fait un Ctrl+S (sauf quand on a rien à sauvegarder)

La scène, même si elle était nouvelle, peut être ouverte après un relancement de l'Asset Editor, et les données qui y avaient été enregistrées sont réstaurées sans problème.

**Comment by cesarl** [comment]
Merci :)

Ca devrait etre fix dans assets_and_exeV1.zip que tu trouvera dans 2 heures sur le drive. Si tu pouvais retester ca serait cool :smile:

**Comment by cesarl** [comment]
Fixed
