### ISSUE TITLE
EngineCoreTest ne trouve pas configuration.json

### ISSUE THREAD

**Issue by BoucherAnthony** [Another-Game-Engine/AGE#527]
EngineCoreTest break au lancement ici : https://github.com/Another-Game-Engine/AGE/blob/master/GameEngine/GameEngine/Engine/Core/Engine.cpp#L183

Le fichier a l'air d'etre present a l'endroit et est remplis de  : 
`{
    "AssetsPath": {
        "string": "../../Assets/Serialized/"
    },
    "ShadersPath": {
        "string": "../../Shaders/"
    }
}`

Les paths sont bon et l'asset editor arrive a cook toutes les assets.

![image](https://cloud.githubusercontent.com/assets/1660030/9184995/a0584ba0-3f6d-11e5-92e3-236a23f5799a.png)
![image](https://cloud.githubusercontent.com/assets/1660030/9185085/239762f8-3f6e-11e5-9edb-3e5f291c0cf6.png)

**Comment by cesarl** [comment]
Merci :)

Ca devrait etre fix dans assets_and_exeV1.zip que tu trouvera dans 2 heures sur le drive. Si tu pouvais retester ca serait cool :smile:
