### ISSUE TITLE
World Editor crash lors de la selection de dragon

### ISSUE THREAD

**Issue by BoucherAnthony** [Another-Game-Engine/AGE#528]
A la selection de l'archetype dragon le program abort a l'un de ses 2 endroits, j'ai essayé de mettre le maximum d'infos sur les screens.

MainThread
![image](https://cloud.githubusercontent.com/assets/1660030/9186028/1f54de02-3f76-11e5-99b0-69f377231c28.png)

PrepareRenderThread
![image](https://cloud.githubusercontent.com/assets/1660030/9186037/3c1a1fca-3f76-11e5-9a1a-3f40784d08c7.png)

**Comment by cesarl** [comment]
Fixed
