### ISSUE TITLE
Il nous faut les mesh de collisions !

### ISSUE THREAD

**Issue by cesarl** [Another-Game-Engine/AGE#548]
Serializes ou calculés au runtime je m'en fout tant que ca fonctionne.
Mesh static concave
Mesh dynamique convexe
!!!!!!!!!!!!!

**Comment by herpec-j** [comment]
On les a, et ils sont fonctionnels. Je crois que Paul n'a juste pas mis
l'option dans l'éditeur, donc ce n'est pas grand chose.

On Tue, Aug 18, 2015, 2:34 AM Cesar Leblic <notifications@github.com> wrote:

> Assigned #548 <https://github.com/Another-Game-Engine/AGE/issues/548> to
> @herpec-j <https://github.com/herpec-j>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Another-Game-Engine/AGE/issues/548#event-384826258>.
>
-- 

Mr. HERPÊCHE Jonathan
Software Engineer at Agueris
+33 (0)6 20 05 13 72

**Comment by cesarl** [comment]
Okay, @paulbaron, peux tu les activer dans l'editeur et tester stp ? Merci

**Comment by paulbaron** [comment]
Ok
