### ISSUE TITLE
glitch bandeau noir 

### ISSUE THREAD

**Issue by cesarl** [Another-Game-Engine/AGE#569]
Disparait progressivement quand on ajoute des points light

![image](https://cloud.githubusercontent.com/assets/1561121/9640093/bd779d5e-517d-11e5-8113-8f540301dffb.png)

**Comment by cesarl** [comment]
![image](https://cloud.githubusercontent.com/assets/1561121/9640135/f612299a-517d-11e5-8c56-e4661d780c01.png)

**Comment by cesarl** [comment]
J'ai enqueté ca vient des points lights

**Comment by cesarl** [comment]
C'est cet appel qui cree cette ligne noir.
@paulbaron , t'as une idee ?
![image](https://cloud.githubusercontent.com/assets/1561121/9641617/ada60976-5185-11e5-9e22-7bf2e25c57d4.png)

**Comment by paulbaron** [comment]
Ya les normales qui sont pétées aussi avec le ateriaux red_dutch.mage

**Comment by paulbaron** [comment]
C'est un bug quand l'entité dans laquelle est la light est scale.
Comme la elle est dans l'entity du sol, elle est scale n'importe comment. Je vais essayer de régler ce probleme.

**Comment by paulbaron** [comment]
Done

**Comment by cesarl** [comment]
Super gg !
